FROM openjdk:11
RUN mkdir /pbl1_redes
WORKDIR /pbl1_redes
COPY /target/pbl1_redes-1.0-SNAPSHOT-jar-with-dependencies.jar /pbl1_redes
CMD ["java","-jar","pbl1_redes-1.0-SNAPSHOT-jar-with-dependencies.jar"]